version: '2'
services:
    helloworld:
      container_name: helloworld
      build:
        context: .
        dockerfile: ./Dockerfile
      ports:
        - '8080:8080'

    nginx:
      container_name: nginx
      image: cvast/cvast-nginx:1.2.0
      restart: unless-stopped
      ports:
        - '80:80'
      environment:
        - NGINX_PROXY_MODE=local
        - NGINX_PROTOCOL=http
        - LOCAL_PROXY_HOST=helloworld
        - LOCAL_PROXY_PORT=8080
        - DOMAIN_NAMES=localhost
        - PUBLIC_MODE=False